#!/usr/bin/env ruby

# from http://errtheblog.com/posts/89-huba-huba

home = File.expand_path('~')

Dir['*'].each do |file|
  next if file =~ /install/
  next if file =~ /README.md/
  next if file =~ /custom/
  next if file =~ /Tech Notes/
  next if file =~ /other_config/
  target = File.join(home, ".#{file}")
  `ln -s #{File.expand_path file} #{target}`
end

target = File.join(home, "TechNotes")
`ln -s "TechNotes" #{target}`

# git push on commit
`echo 'git push' > .git/hooks/post-commit`
`chmod 755 .git/hooks/post-commit`
